version: '3'

services:
  MyClimate:
    image: docker.io/bitnami/laravel:9
    ports:
      - '8000:8000'
    environment:
      - DB_CONNECTION=sqlite
      - DB_HOST=127.0.0.1
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_DATABASE=database
    volumes:
      - './MyClimate:/app'
